<?php

namespace ContainerQbKtVeK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_1eYq0k6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.1eYq0k6' shared service.
     *
     * @return \App\Service\SpotifyApiService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\AlbumController::index()": the $spotifyApiService argument is type-hinted with the non-existent class or interface: "App\\Service\\SpotifyApiService".');
    }
}
