<?php

namespace ContainerQbKtVeK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A6yJV4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a_6yJV4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a_6yJV4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'spotifyApiService' => ['privates', '.errored.1eYq0k6', NULL, 'Cannot determine controller argument for "App\\Controller\\AlbumController::index()": the $spotifyApiService argument is type-hinted with the non-existent class or interface: "App\\Service\\SpotifyApiService".'],
        ], [
            'spotifyApiService' => '?',
        ]);
    }
}
