<?php

namespace ContainerTCENoFD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SCdSo7hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SCdSo7h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SCdSo7h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'musique' => ['privates', '.errored..service_locator.SCdSo7h.App\\Entity\\Musique', NULL, 'Cannot autowire service ".service_locator.SCdSo7h": it references class "App\\Entity\\Musique" but no such service exists.'],
        ], [
            'musique' => 'App\\Entity\\Musique',
        ]);
    }
}
