<?php

namespace ContainerTCENoFD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GT6g1WVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gT6g1WV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gT6g1WV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'musique' => ['privates', '.errored..service_locator.gT6g1WV.App\\Entity\\Musique', NULL, 'Cannot autowire service ".service_locator.gT6g1WV": it references class "App\\Entity\\Musique" but no such service exists.'],
            'musiqueRepository' => ['privates', 'App\\Repository\\MusiqueRepository', 'getMusiqueRepositoryService', true],
        ], [
            'musique' => 'App\\Entity\\Musique',
            'musiqueRepository' => 'App\\Repository\\MusiqueRepository',
        ]);
    }
}
