<?php

namespace ContainerTCENoFD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EsknOpgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EsknOpg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EsknOpg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'musiqueRepository' => ['privates', 'App\\Repository\\MusiqueRepository', 'getMusiqueRepositoryService', true],
        ], [
            'musiqueRepository' => 'App\\Repository\\MusiqueRepository',
        ]);
    }
}
