<?php

namespace ContainerTCENoFD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMusiqueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SCdSo7h.App\Entity\Musique' shared service.
     *
     * @return \App\Entity\Musique
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SCdSo7h": it references class "App\\Entity\\Musique" but no such service exists.');
    }
}
