<?php

namespace ContainerPxJNgmF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0Lp2UdLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0Lp2UdL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0Lp2UdL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AlbumController::delete' => ['privates', '.service_locator.O0qDrEY', 'get_ServiceLocator_O0qDrEYService', true],
            'App\\Controller\\AlbumController::edit' => ['privates', '.service_locator.O0qDrEY', 'get_ServiceLocator_O0qDrEYService', true],
            'App\\Controller\\AlbumController::index' => ['privates', '.service_locator.a1X_Afj', 'get_ServiceLocator_A1XAfjService', true],
            'App\\Controller\\AlbumController::new' => ['privates', '.service_locator.a1X_Afj', 'get_ServiceLocator_A1XAfjService', true],
            'App\\Controller\\AlbumController::show' => ['privates', '.service_locator.KpmPeGn', 'get_ServiceLocator_KpmPeGnService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AlbumController:delete' => ['privates', '.service_locator.O0qDrEY', 'get_ServiceLocator_O0qDrEYService', true],
            'App\\Controller\\AlbumController:edit' => ['privates', '.service_locator.O0qDrEY', 'get_ServiceLocator_O0qDrEYService', true],
            'App\\Controller\\AlbumController:index' => ['privates', '.service_locator.a1X_Afj', 'get_ServiceLocator_A1XAfjService', true],
            'App\\Controller\\AlbumController:new' => ['privates', '.service_locator.a1X_Afj', 'get_ServiceLocator_A1XAfjService', true],
            'App\\Controller\\AlbumController:show' => ['privates', '.service_locator.KpmPeGn', 'get_ServiceLocator_KpmPeGnService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AlbumController::delete' => '?',
            'App\\Controller\\AlbumController::edit' => '?',
            'App\\Controller\\AlbumController::index' => '?',
            'App\\Controller\\AlbumController::new' => '?',
            'App\\Controller\\AlbumController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AlbumController:delete' => '?',
            'App\\Controller\\AlbumController:edit' => '?',
            'App\\Controller\\AlbumController:index' => '?',
            'App\\Controller\\AlbumController:new' => '?',
            'App\\Controller\\AlbumController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
