<?php

namespace ContainerPxJNgmF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlbumService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KpmPeGn.App\Entity\Album' shared service.
     *
     * @return \App\Entity\Album
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KpmPeGn": it references class "App\\Entity\\Album" but no such service exists.');
    }
}
