<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTCENoFD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTCENoFD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTCENoFD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTCENoFD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTCENoFD\App_KernelDevDebugContainer([
    'container.build_hash' => 'TCENoFD',
    'container.build_id' => '22f96170',
    'container.build_time' => 1680738034,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTCENoFD');
