<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_album_index' => [[], ['_controller' => 'App\\Controller\\AlbumController::index'], [], [['text', '/album/']], [], [], []],
    'app_album_new' => [[], ['_controller' => 'App\\Controller\\AlbumController::new'], [], [['text', '/album/new']], [], [], []],
    'app_album_show' => [['id'], ['_controller' => 'App\\Controller\\AlbumController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/album']], [], [], []],
    'app_album_edit' => [['id'], ['_controller' => 'App\\Controller\\AlbumController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/album']], [], [], []],
    'app_album_delete' => [['id'], ['_controller' => 'App\\Controller\\AlbumController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/album']], [], [], []],
    'app_musique_index' => [[], ['_controller' => 'App\\Controller\\MusiqueController::index'], [], [['text', '/musique/']], [], [], []],
    'app_musique_new' => [[], ['_controller' => 'App\\Controller\\MusiqueController::new'], [], [['text', '/musique/new']], [], [], []],
    'app_musique_show' => [['id'], ['_controller' => 'App\\Controller\\MusiqueController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/musique']], [], [], []],
    'app_musique_edit' => [['id'], ['_controller' => 'App\\Controller\\MusiqueController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/musique']], [], [], []],
    'app_musique_delete' => [['id'], ['_controller' => 'App\\Controller\\MusiqueController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/musique']], [], [], []],
];
